version: "3"

######################
# NOMAD SERVERS EAST #
######################
# 192.168.1.120 --- 192.168.1.129
services:
  east-nomad0:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - east-consul3
      - east-consul4
      - east-consul5
    hostname: east-nomad0
    volumes:
      - ./data/east/east-nomad0/nomad:/etc/nomad.d
      - ./data/east/east-nomad0/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.120

  east-nomad1:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - east-consul3
      - east-consul4
      - east-consul5
    hostname: east-nomad1
    volumes:
      - ./data/east/east-nomad1/nomad:/etc/nomad.d
      - ./data/east/east-nomad1/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.121


  east-nomad2:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - east-consul3
      - east-consul4
      - east-consul5
    hostname: east-nomad2
    volumes:
      - ./data/east/east-nomad2/nomad:/etc/nomad.d
      - ./data/east/east-nomad2/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.122


######################
# NOMAD SERVERS west #
######################
# 192.168.1.220, 221, 222 ---> 192.168.1.229
  west-nomad0:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - west-consul3
      - west-consul4
      - west-consul5
    hostname: west-nomad0
    volumes:
      - ./data/west/west-nomad0/nomad:/etc/nomad.d
      - ./data/west/west-nomad0/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.220

  west-nomad1:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - west-consul3
      - west-consul4
      - west-consul5
    hostname: west-nomad1
    volumes:
      - ./data/west/west-nomad1/nomad:/etc/nomad.d
      - ./data/west/west-nomad1/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.221


  west-nomad2:
    build:
      context: .
      dockerfile: nomad.dockerfile
    depends_on:
      - west-consul3
      - west-consul4
      - west-consul5
    hostname: west-nomad2
    volumes:
      - ./data/west/west-nomad2/nomad:/etc/nomad.d
      - ./data/west/west-nomad2/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.222

#######################
# CONSUL SERVERS EAST #
#######################
# 192.168.1.130, 131, 132 ---> 192.168.1.139

  east-consul3:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: east-consul3
    volumes:
      - ./data/east/east-consul3/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.130

  east-consul4:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: east-consul4
    volumes:
      - ./data/east/east-consul4/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.131

  east-consul5:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: east-consul5
    volumes:
      - ./data/east/east-consul5/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.132


#######################
# CONSUL SERVERS west #
#######################
# 192.168.1.230 --- 192.168.1.239

  west-consul3:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: west-consul3
    volumes:
      - ./data/west/west-consul3/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.230

  west-consul4:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: west-consul4
    volumes:
      - ./data/west/west-consul4/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.231

  west-consul5:
    build:
      context: .
      dockerfile: consul.dockerfile
    hostname: west-consul5
    volumes:
      - ./data/west/west-consul5/consul:/etc/consul.d
    networks: 
      net_hashi:
        ipv4_address: 192.168.1.232

networks:
  net_hashi:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          # ip-range: 192.168.1.128/25